name: Publish docker images

on:
  push:
    branches: master

  workflow_dispatch:

jobs:
  build_and_deploy_everywhere:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build . -t docker-spring
          rev= git rev-parse --short HEAD
          docker tag docker-spring jesorel/docker-spring:$rev
          docker tag docker-spring 244530008913.dkr.ecr.eu-west-1.amazonaws.com/mime005:$rev
      - name: Deploy dockerhub
        run: | 
          docker login -u jesorel --password ${{ secrets.DOCKERHUB_TOKEN }}
        docker push jesorel/docker:$rev
      - name: Deploy to aws ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password | docker login -u AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com/mime005
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/mime005:$rev

